### ISSUE TITLE
[bug] localhost:3000 is redirected if slash is missing at the end of the URL

### ISSUE THREAD

**Issue by Striffly** [roots/bud#1210] opened 2022-02-28 16:08 UTC
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Expected Behavior

No redirection if / is missing at the end of URL

### Actual Behavior

When a slash is missing at the end of the URL, localhost:3000 is redirected to proxy URL (mywebsite.localhost)

### Steps To Reproduce

1. Go to localhost:3000/test (no slash at the end)
2. Page is redirected to mywebsite.localhost/test/

### version

@roots/bud/5.4.0

### What package manager are you using?

yarn classic

### version

1.22.17

### Are you using pnpm?

- [ ] yes
- [X] no

**Comment by kellymears** [comment] 2022-02-28 21:27
thanks for the report. i'll look into this.

i'm guessing it has to do with a `/` being appended to `origin` somewhere in the proxy middleware options 

ref: https://nodejs.org/api/url.html#urlorigin

**Comment by kellymears** [comment] 2022-03-15 20:09
Is this still an issue > 5.5.0?

**Comment by Striffly** [comment] 2022-03-15 22:59
Yes, issue still exists

**Comment by woutervanerp** [comment] 2022-03-25 14:30
Same for me. Came here for answers :)
Didn't know ending urls with forward slash 'fixes' this

**Comment by kellymears** [comment] 2022-03-29 23:09
This was ultimately reproducible and is assuredly fixed as of 5.7.4.

**Closed as completed by kellymears** 2022-03-29 23:09 UTC
Labels: bug

**Comment by Striffly** [comment] 2022-05-09 10:11
https://discourse.roots.io/t/err-http-headers-sent-with-yarn-bud-dev/22953/7 I think this issue is related !

**Comment by Striffly** [comment] 2022-09-28 11:38
@kellymears This issue appears again in 6.3.3

**Comment by Striffly** [comment] 2022-10-03 14:12
@kellymears This issue also appears in 6.4.4

**Comment by retlehs** [comment] 2022-10-03 14:14
I can't reproduce. It's likely related to your webserver — not Bud.

**Comment by dustingrofthenumber** [comment] 2023-09-06 00:41
If anyone is able to fix their webserver configuration based on this discussion, please let us know!

**Comment by Striffly** [comment] 2023-11-13 03:10
I still have this issue with latest bud / sage version 😅

My apache vhost : 

```
<VirtualHost *:80>
    DocumentRoot "/xxx/web/"
    DirectoryIndex index.php index.html
    ServerName xxx.localhost
    ServerAlias xxx.localhost
    ErrorLog "/var/log/httpd/xxx.local-error_log"
    CustomLog "/var/log/httpd/xxx.local-access_log" common

    <Directory "/xxx/web/">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        Header set Access-Control-Allow-Origin "*"
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php82-fpm/php82-fpm.sock|fcgi://localhost/"
    </FilesMatch>
</VirtualHost>
```

And my `/etc/httpd/conf/httpd.conf` is the original one...
I still have this issue since 2-3 years, on multiple OS, with nginx, apache, or LAMP & MAMP
